word: input/test.txt
	./../bin/convert -l 0x10 -d f -f input/test.txt -t output/test.txt
	./../bin/convert -l 0x03 -d b -f output/test.txt -t input/test_benga.txt
	./../bin/convert -l 0x06 -d b -f output/test.txt -t input/test_devan.txt
	./../bin/convert -l 0x05 -d b -f output/test.txt -t input/test_burm.txt
